source "https://rubygems.org"

gem "sinatra"
gem "sinatra-activerecord"
gem "sqlite3"
gem "httparty"
gem "json"

# @ telmo - a brief search led me to the previous packages... I may need to update/swap them in time!

gem "rackup"
gem "puma"

# @ telmo - additions following error messages -- need to read about it